<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>6b76c772-5fd9-4082-9309-f8c6805855da</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2"/>
        <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.1"/>
        <PackageReference Include="Azure.Identity" Version="1.21.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Controllers\"/>
    </ItemGroup>

</Project>
