@local = http://localhost:8080
@azure = https://ca-bengle-api.bravecliff-f51f7703.eastus2.azurecontainerapps.io

### Local (dotnet run --launch-profile http)
GET {{local}}/bengle/api/players
Accept: application/json

### Azure (Container App)
GET {{azure}}/bengle/api/players
Accept: application/json

###
