name: setup-node
description: "Setup Node.js, cache dependencies, and install using pnpm"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Cache pnpm store
      id: cache_pnpm
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
