
name: publish-to-github-pages

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/workflows/setup-node

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          inject: false

      - name: Build with Next.js
        run: pnpm build

      - name: Debug - List directory
        run: ls

      - name: Debug - List output directory
        run: ls -al ./out

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
